### ISSUE TITLE
Opened tab not connected

### ISSUE THREAD

**Issue by maxoku** [MethodGrab/firefox-open-image-in-new-tab#5]
Normally when a new tab is opened it's connected to the tab from which it was opened. Thanks to that after closing it the previous tab is being automatically selected (focused) instead of the tab to the right (which happens if there's no connection). Or if opened in the background tab allows new tabs to be opened after previously opened tab instead to again on right of current tab.

Please add that connection, so when I close the tab with image it would return to the previous tab automatically. And of course open new tabs after previous opened background tab.

**Comment by MethodGrab** [comment]
Thanks for this suggestion, it's a much smoother UX!

Published on AMO as v1.0.0.

**Comment by maxoku** [comment]
Yes, it works. Thanks for fixing.
