### ISSUE TITLE
Respect the "When you open a new tab, switch to it immediately" setting in about:preferences

### ISSUE THREAD

**Issue by dmattera** [MethodGrab/firefox-open-image-in-new-tab#7]
The "Shift+click" option to do this is nice but definitely not ideal especially since this is user-visible setting in the browser (as opposed to something tucked away in about:config).  If a user is disabling this setting for all other links they open, there's no reason that I can think of to believe they wouldn't want the same behavior when opening images as well.

Ideally, you would default to whatever the browser setting is set to and then the "Shift+click" option would just do the opposite for those times when you want non-default behavior.

**Comment by MethodGrab** [comment]
That does sound like a reasonable way to expect the extension to behave however I don't think it's possible to do this **automatically** with the available webextension APIs:
1. The [`browser.tabs.create` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) will default to `active: true` if `active` is not specified.  
You might expect the default value of `active` to be affected by `browser.tabs.loadInBackground`, but apparently that's not the case (I just tried it).
2. As far as I can tell, webextensions only have access to a very limited subset of browser preferences through the [`browser.browserSettings` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings) and `browser.tabs.loadInBackground` is not included.

The only way to achieve the outcome you want would be to add a new configuration option to **this extension** that allows you to **manually** specify the default behaviour (open the image in background vs. foreground tab) and then, as you said, use <kbd>SHIFT</kbd> as the modifier when you want the opposite behaviour.

**Comment by brainchild0** [comment]
> to add a new configuration option to **this extension** that allows you to **manually** specify the default behaviour

I would consider this idea a good workaround for the limitations in WebExtensions.

It would be a useful enhancement since jumping to a new tab is not preferred in many cases.

If you have a chance, and  the limitation is not already reported in Bugzilla, then you might open a request, identifying yourself as an extensions developer.

**Comment by regs01** [comment]
Couldn't it be just a checkbox in extension settings to swap Shift action - Open in background tab by default.
So if checked holding Shift will bring a new tab to foreground instead.

**Comment by dmattera** [comment]
> Couldn't it be just a checkbox in extension settings to swap Shift action - Open in background tab by default.
> So if checked holding Shift will bring a new tab to foreground instead.

Yes, but this issue was specifically requesting that the addon automatically detect and respect the setting that users have set in Firefox's main preferences screen by default (the one called "When you open a new tab, switch to it immediately").

per @MethodGrab's response above, the request doesn't appear possible at the moment but said pretty much the same as you in that setting this manually in the addon's settings page would be the (only) way to go with acheiving this

**Comment by glubsy** [comment]
I face the same issue. I would like to see a checkbox to invert the default behaviour when holding shift. 

By default loading in background is much preferred.

**Comment by MethodGrab** [comment]
> The only way to achieve the outcome you want would be to add a new configuration option to **this extension** that allows you to **manually** specify the default behaviour (open the image in background vs. foreground tab) and then, as you said, use SHIFT as the modifier when you want the opposite behaviour.

This partial fix (#9) is published on AMO as v1.1.0.

**Comment by dmattera** [comment]
Just wanted to circle back and say thanks again for this fix @MethodGrab. 

Being able to have "new image tabs" open in the background by default rather than having to Ctrl+click for past couple of months now has been a huge boost my workflow. Thank you!
